services:
  database:
    image: mysql:8.0
    container_name: orders-app-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: orders-app-php
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - database

volumes:
  database_data:
